//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Swipe/InputActions/SwipeActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SwipeActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SwipeActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SwipeActions"",
    ""maps"": [
        {
            ""name"": ""default"",
            ""id"": ""c5387631-726e-4402-ba2c-e47f9145f783"",
            ""actions"": [
                {
                    ""name"": ""StartSwipe"",
                    ""type"": ""Button"",
                    ""id"": ""0c2d36be-be5b-4de0-a352-e57cb3d04d64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EndSwipe"",
                    ""type"": ""Button"",
                    ""id"": ""cd6be849-9ac2-4ba1-a780-52c3186974c5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d12db527-3ef9-47a6-81ae-8d271d4165de"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1937052e-02ec-48e3-b014-2c38a679ba58"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EndSwipe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // default
        m_default = asset.FindActionMap("default", throwIfNotFound: true);
        m_default_StartSwipe = m_default.FindAction("StartSwipe", throwIfNotFound: true);
        m_default_EndSwipe = m_default.FindAction("EndSwipe", throwIfNotFound: true);
    }

    ~@SwipeActions()
    {
        UnityEngine.Debug.Assert(!m_default.enabled, "This will cause a leak and performance issues, SwipeActions.default.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // default
    private readonly InputActionMap m_default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_default_StartSwipe;
    private readonly InputAction m_default_EndSwipe;
    public struct DefaultActions
    {
        private @SwipeActions m_Wrapper;
        public DefaultActions(@SwipeActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartSwipe => m_Wrapper.m_default_StartSwipe;
        public InputAction @EndSwipe => m_Wrapper.m_default_EndSwipe;
        public InputActionMap Get() { return m_Wrapper.m_default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @StartSwipe.started += instance.OnStartSwipe;
            @StartSwipe.performed += instance.OnStartSwipe;
            @StartSwipe.canceled += instance.OnStartSwipe;
            @EndSwipe.started += instance.OnEndSwipe;
            @EndSwipe.performed += instance.OnEndSwipe;
            @EndSwipe.canceled += instance.OnEndSwipe;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @StartSwipe.started -= instance.OnStartSwipe;
            @StartSwipe.performed -= instance.OnStartSwipe;
            @StartSwipe.canceled -= instance.OnStartSwipe;
            @EndSwipe.started -= instance.OnEndSwipe;
            @EndSwipe.performed -= instance.OnEndSwipe;
            @EndSwipe.canceled -= instance.OnEndSwipe;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnStartSwipe(InputAction.CallbackContext context);
        void OnEndSwipe(InputAction.CallbackContext context);
    }
}
